# Backend Build & Test Pipeline
trigger:
  branches:
    include:
      - dev_maaroufi
      - dev_marouane
      - dev_zouhair
      - main
  paths:
    include:
      - 'src/**'
      - 'pom.xml'
      - 'azure-pipelines-backend.yml'

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_VERSION: '17'

steps:
- checkout: self
  displayName: 'Checkout repository'

- task: JavaToolInstaller@0
  displayName: 'Set up JDK'
  inputs:
    versionSpec: $(JAVA_VERSION)
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  displayName: 'Build with Maven (No Tests)'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.$(JAVA_VERSION)'

- task: PublishPipelineArtifact@1
  displayName: 'Upload JAR artifact'
  inputs:
    targetPath: 'target/*.jar'
    artifact: 'backend-jar'
    publishLocation: 'pipeline'