name: Backend CI/CD for TutorConnect 

on:
  push:
    branches: [main, develop]
    paths:
      - 'TutorConnect-app/**'

env:
  AZURE_WEBAPP_NAME: 'tutorconnect-app'      
  AZURE_RESOURCE_GROUP: 'tutorconnect-rg'    
  ACR_LOGIN_SERVER: 'tutorconnectacr.azurecr.io'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: TutorConnect-app
      run: mvn clean package -DskipTests

    - name: Build Docker image
      working-directory: TutorConnect-app
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/tutorconnect-backend:${{ github.sha }} .

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Push to Azure Container Registry
      run: |
        docker push ${{ env.ACR_LOGIN_SERVER }}/tutorconnect-backend:${{ github.sha }}

    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        images: ${{ env.ACR_LOGIN_SERVER }}/tutorconnect-backend:${{ github.sha }}