# Utiliser l'image officielle OpenJDK comme image de base
FROM openjdk:17-jdk-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier JAR de l'application dans le conteneur
COPY target/TutorConnect-app.jar /app/TutorConnect-app.jar

# Exposer le port 8080 pour accéder à l'application
EXPOSE 8080

# Commande pour exécuter l'application Spring Boot
CMD ["java", "-jar", "TutorConnect-app.jar"]
