name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    name: Test Spring Boot Backend
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tutor_connect
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Test with Maven
        run: mvn -B test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tutor_connect
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

  frontend-build:
    name: Build React Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd tutorconnectfrontend
          npm ci
          npm install react-router-dom axios
      
      - name: Build production bundle
        run: CI=false npm run build
        working-directory: tutorconnectfrontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  docker-build-verify:
    name: Verify Docker Builds
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-build]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build backend image
        run: docker build -t backend .
      
      - name: Build frontend image
        run: docker build -t frontend ./tutorconnectfrontend

  docker-compose-test:
    name: Test Docker Compose
    runs-on: ubuntu-latest
    needs: docker-build-verify
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          install-compose: true
      
      - name: Start containers
        run: docker-compose up -d --build
      
      - name: Wait for containers to be ready
        run: |
          timeout 180 bash -c 'until docker-compose ps | grep "healthy"; do sleep 10; done'
      
      - name: Check running containers
        run: docker-compose ps
      
      - name: Verify backend health
        run: |
          curl --retry 5 --retry-delay 10 --retry-connrefused -f http://localhost:8080/actuator/health
      
      - name: Collect logs if failed
        if: failure()
        run: |
          docker-compose logs --no-color > docker-compose.logs
          echo "=== Service status ==="
          docker-compose ps -a
      
      - name: Upload logs artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-logs
          path: docker-compose.logs
      
      - name: Stop containers
        if: always()
        run: docker-compose down -v --remove-orphans
