name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  backend-test:
    name: Test Spring Boot Backend
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tutor_connect
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Test with Maven
        run: mvn -B test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tutor_connect
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
  frontend-build:
    name: Build React Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd tutorconnectfrontend
          npm install
          npm install react-router-dom axios
      
      - name: Build production bundle (ignore ESLint warnings)
        run: CI=false npm run build
        working-directory: tutorconnectfrontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
  docker-build-verify:
    name: Verify Docker Builds
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-build]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build backend image
        run: docker build -t backend .
      
      - name: Build frontend image
        run: docker build -t frontend ./tutorconnectfrontend

  docker-compose-test:
    name: Test Docker Compose
    runs-on: ubuntu-latest
    needs: docker-build-verify
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tutor_connect
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v3
        with:
          version: 'v2.24.5'
      
      - name: Start containers
        run: docker compose up -d --build
      
      - name: Wait for services
        run: |
          echo "Waiting for services to start..."
          sleep 15
          docker compose ps
          docker compose logs backend
      
      - name: Verify backend health
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:8080/actuator/health >/dev/null; then
              echo "Backend is healthy!"
              exit 0
            fi
            echo "Attempt $i/10 - Backend not ready yet..."
            sleep 10
          done
          echo "Backend health check failed"
          docker compose logs
          exit 1
      
      - name: Cleanup
        run: docker compose down
        if: always()
